my_string = input('Напишите текст: ')
print('В Вашем тексте', len(my_string), 'символов')
print(my_string.upper())
print(my_string.lower())
print(my_string.replace(' ', ''))
print(my_string[0])
print(my_string[-1])